# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-arm
    - name: Build runtime required version
      run: dotnet build --no-restore --no-self-contained -r linux-arm -c Release src/ReTerm/ReTerm.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip artifact for runtime deployment
      run: zip --junk-paths release-required-dotnet-runtime.zip ./src/ReTerm/bin/Release/net6.0/linux-arm/* -r   
    - name: Build monolithic version
      run: dotnet publish -r linux-arm --self-contained true -p:PublishSingleFile=true -p:PublishedTrimmed=true -p:PublishReadyToRun=true -p:Configuration=Release -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRunShowWarnings=true src/ReTerm/ReTerm.csproj    
    - name: Copy shell script to monolithic version output
      run: cp src/ReTerm/ReTerm.sh ./src/ReTerm/bin/Release/net6.0/linux-arm/publish/
    - name: Zip artifact for monolithic deployment
      run: zip --junk-paths release-no-dotnet-runtime.zip ./src/ReTerm/bin/Release/net6.0/linux-arm/publish/* -r         
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: Latest automatically built release
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./release-required-dotnet-runtime.zip
        asset_name: release-required-dotnet-runtime.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-monolithic
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./release-no-dotnet-runtime.zip
        asset_name: release-no-dotnet-runtime.zip
        asset_content_type: application/zip
